### ISSUE TITLE
Доработки

### ISSUE THREAD

**Issue by IvanMurakhovskii** [andrey-stepantsev/react-exercises#18]
- счетчик шагов увеличивается при любом нажатии на ячейку, а не только когда она перемещается на игровом поле; 

- весь интерфейс расположен не по центру экрана;

- непонятно, чем отличаются 2 режима игры;

**Comment by andrey-stepantsev** [comment]
По замечаниям согласен. Исправляю.

Режимы игры действительно пока не имеют никакого смысла и ничем не отличаются. Для выпускного проекта реализую несколько режимов.

**Comment by andrey-stepantsev** [comment]
Баг с подсчетом количества шагов и центрирование интерфейса исправлены в PR: https://github.com/andrey-stepantsev/react-exercises/pull/17.

Режимы игры будут переработаны и рассмотрены отдельно.
