### ISSUE TITLE
Доработки №2

### ISSUE THREAD

**Issue by Shazlogic** [andrey-stepantsev/react-exercises#19]
Предложения:
1. Обновить интерфейс, и адаптировать дизайн. Позиционировать интерфейс по центру, на больших экранах неудобно играть.
2. По кнопке Reset сбрасывать игру и сразу начинать, так как приходится нажимать кнопку New Game.
3. Добавить свою историю игр или рекорды.
4. При нажатии на кнопку Reset сбрасываются Game Settings, это лишнее при наличии двух полей, пользователю приходится заново выбирать настройки. Рекомендую сбрасывать только игровое поле.
5. Нет чувства оживленности игры, после нескольких минут становится грустно и хочется закрыть игру. Добавь аудио, например 8bit характерной для таких типов игр или при клике на кнопки игровых блоков производить звук перемещения.

Баг:
1. Начал новую игру поле 2х2, хочу сменить поле на 4х4 нажимаю New Game ничего не происходит, только после кнопки Reset могу начать новую игру.

**Comment by andrey-stepantsev** [comment]
Интерфейс сейчас в процессе полной переработки. Так что скоро будет все красиво.

Сброс игры и начало новой игры доработаю.

По музыке очень интересное приложение. В выпускной проект добавлю. Как и графики с историей игр и статистикой.
